### ISSUE TITLE
ViewModel having different injection approach

### ISSUE THREAD

**Issue by devAseemSharma** [MindorksOpenSource/android-mvvm-architecture#15]
I have observed that in some classes like SplashActivity and LoginActivity ViewModel is directly been injected without using ViewModelProviderFactory.class. 
   But in MainActivity class ViewModel is not directly injected, it is instantiated using ViewModelProviderFactory.class I do not get the purpose these two approach.

I believe this is done due to the fact that Login and Splash screen do not support saving state of the view when screen is rotated, but MainActivity does. Is it true?

**Comment by amitshekhariitbhu** [comment]
Yes you are correct

**Comment by devAseemSharma** [comment]
Thanks
