### ISSUE TITLE
missing import com.mindorks.framework.mvvm.di.component.DaggerAppComponent;

### ISSUE THREAD

**Issue by s3hengwu** [MindorksOpenSource/android-mvvm-architecture#21]
missing import com.mindorks.framework.mvvm.di.component.DaggerAppComponent;

**Comment by amitshekhariitbhu** [comment]
Rebuild the project, it will be automatically created.

**Comment by s3hengwu** [comment]
Okay!

**Comment by Anu07** [comment]
Still facing problem .ppls help.getting following message:
DaggerDemoApplication cannot be provided without an @Inject constructor or from an @Provides-annotated method. This type supports members injection but cannot be implicitly provided.
