### ISSUE TITLE
How to achieve MVVM without Room

### ISSUE THREAD

**Issue by aptgopal** [MindorksOpenSource/android-mvvm-architecture#28]
Hi 

First off all thanks for the nice example for mvvm. Actually my project we don't want to use local database(Room). Can you help me how I can achieve the same using this project as reference.

Thanks in Advance.

**Comment by rayworks** [comment]
@aptgopal , Since `DbHelper` is an interface, you can simply replace its implementation class `AppDbHelper` ( related to Room) with another one. Don't forget also update the injections in `AppModule`.
