### ISSUE TITLE
Room Persistence Library

### ISSUE THREAD

**Issue by dhavaljivani** [MindorksOpenSource/android-mvvm-architecture#3]
Hello,

I have seen your MVVM example Good example,You have implemented **Room Persistence Library** code using **dagger2** but i can't find any use of this code so can you please help me where you have used Room Persistence Library for insert,update,delete data into **SQLite database**.

Thank you

**Comment by amitshekhariitbhu** [comment]
Dagger2 is only used for injecting the object where ever it is required.
