### ISSUE TITLE
blogViewModel and openSourceViewModel VS ViewModelProviderFactory

### ISSUE THREAD

**Issue by omidjoon** [MindorksOpenSource/android-mvvm-architecture#54]
hi i checked both previous and new code and i have a question. as i see, you move all viewmodels to ViewModelProviderFactory and remove them from modules. Although you mention new OpenSourceViewModel(dataManager,schedulerProvider); and  new BlogViewModel(dataManager,schedulerProvider); in ViewModelProviderFactory, you also provide them in OpenSourceFragmentModule and BlogFragmentModule. why did you do this ?
thanks

**Comment by jyotid** [comment]
hey,
Thanks for pointing it out.
This looks like a mistake and we have rectified it and it will be available soon in the master branch.
Reason being , now all the VM creation is delegated to VMFactory and hence there should not be any VM creation from any of the modules.

**Comment by omidjoon** [comment]
Thanks for answering me. you can close this issue
